[과제] 6주차 세미나 과제
IN-SOPT-ANDROID/chaeyeon-jeon pull request #10
Opened 2022-12-02 02:38 UTC by b1urrrr

```
하다보니 PR이 너무 커져서.. 보기 힘드시겠네요.. 죄삼다...
```
- #8 
<br>

## 필수 과제
- 홈 화면도 UI Layer 만들어보기
- 경고 정도는 이제 쉽자나?

## 심화 과제
- 양방향 데이터바인딩으로 코드 로직 개선

## 도전 과제
- Data Layer 분리 
_→ 합세 코드 참고하면서 어찌저찌 분리하긴 했는데 아직 완전히 이해하진 못해서 코드 뜯어보면서 계속 공부하겠습니다! 부족한 부분 많이 알려주세요!_

## 실행 화면
<img src="https://user-images.githubusercontent.com/70993562/205201421-ba31fba3-4582-43b0-aba3-adee9b8e1e6d.gif" width=30% height=30%>

2022-12-02 04:16 UTC, papajj06 reviewed
째연이 못하는게머냐!!잘한다!!ㅎㅎ

2022-12-02 04:58 UTC, KWY0218 requested changes
과제 하시느라 수고하셨습니다!!!
코루틴에 di에 mvvm에... 최고 ~ 😄👍

2022-12-02 04:58 UTC, KWY0218 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
false 로 바꿔주세요 ~

2022-12-02 04:58 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                }
`runcatching`을 사용하면 `.onSuccess` 에는 200 대가 들어가고, `.onFailure` 안에는 500에러 뿐만 아니라 400에러도 자동으로 들어갑니다. 그래서 Response를 안 덮어도 됩니다..!

2022-12-02 04:58 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/api/FollowerService.kt
> +    ): Response<ResponseGetFollowerListDto>
```suggestion
    ): ResponseGetFollowerListDto
```
이렇게 해도 됩니다 ~

2022-12-02 04:58 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                        _followerList.value = tempFollowerList
```suggestion
                        _followerList.value = response.body()?.data!!
```
` response.body()?.data!!` 는 항상 `followerList.value` 내에 있는 주소 값과 다르기 때문에
이런 식으로 해도 livedata가 변화를 감지합니다

2022-12-02 04:58 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +            finish()
해당 함수는 `success` 일 때를 감지해서 activity를 종료시키는 함수인 것 같아 보이는데,
`observeStateMessage` 함수 내에서 토스트만 띄우지 말고 `State.SUCCESS` 일 때 해당 로직을 실행한다면 
loginResult 변수를 없앨 수 있을 것 같습니다..!

2022-12-02 04:58 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +    }
```suggestion
        viewModelScope.launch {
            authRepository.login(RequestLoginDto(email, password))
                .onSuccess { 
                    _stateMessage.value = State.SUCCESS
                }
                .onFailure {
                    _stateMessage.value = State.SERVER_ERROR
                }
        }
    }
```
if문을 지워도 성공일 때만 `onsuccess` 안에 들어오기 때문에 이런 식으로 코드를 줄일 수 있을 것 같습니다

2022-12-02 04:58 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/di/RepositoryModule.kt
> +    ): FollowerRepository = followerRepositoryImpl
제 [세미나4 pr](https://github.com/IN-SOPT-ANDROID/wonyong-kang/pull/8) 에 달린 리뷰 그대로 복붙해왔습니다 ~

Provides의 경우 외부 라이브러리의 클래스를 생성하거나, 빌더패턴으로 객체를 생성하는 경우 보통 사용됩니다.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/70698151/201682813-6a8e5343-4aac-49b7-a8e5-3a4ba0cf7465.png">

![image](https://user-images.githubusercontent.com/70698151/201683499-4204a649-5a17-44a6-b4de-1afc9abd4e15.png)

현재 코드의 경우 **Binds**로 처리할 수 있는 케이스입니다. Provides로도 물론 주입이 가능한 건 맞지만, 컴파일 타임에서 Binds의 이점이 크기 때문에 Binds를 활용하는 게 좋을 것 같습니다! 자세한 설명은 공식 문서 링크 참조하시면 좋을 것 같네요!

[공식문서](https://developer.android.com/training/dependency-injection/hilt-android?hl=ko#inject-interfaces)

2022-12-02 07:13 UTC, b1urrrr commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
네!! 서버 안 될 때 에뮬레이터 돌려보느라 바꿔놨던 걸 깜빡했네요😅
감사합니다~

2022-12-02 07:39 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                        _followerList.value = tempFollowerList
아이고 제가 괜히 for문으로 복잡하게 처리하고 있었네요!
감사합니다 ~

2022-12-02 07:46 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                }
헉.. 알아서 Failure로 처리해주는군요!
그러면 onFailure에서 400 에러인 경우를 `FAIL`로 따로 처리해주는 게 좋을까요?

2022-12-02 07:50 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                }
![image](https://user-images.githubusercontent.com/82709044/205242538-6ed3620f-ab3a-4a7b-88e7-0ced00e3a149.png)
요런 식으로 throwable 을 HttpException으로 캐스팅 하고 400일 때, 500일 때 나눠도 됩니다~ !
_사진에서 나온 `NO_SIGN_UP` 은 상수~_

2022-12-02 07:51 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                }
감삼다!!!

2022-12-02 09:59 UTC, KWY0218 approved these changes
굳입니당~👍

2022-12-02 11:23 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/di/RepositoryModule.kt
> +    ): FollowerRepository = followerRepositoryImpl
힐트 어노테이션들이 각각 어떤 역할을 하는지 더 공부해봐야겠어요...🔥
감사합니다!!

2022-12-04 07:47 UTC, waterminn approved these changes
수고하셨습니다!! 코드가 상당히 어려워졌네요👍

2022-12-04 07:47 UTC, wateralsie commented on app/src/main/res/layout/activity_sign_up.xml
> +            app:layout_constraintTop_toBottomOf="@id/et_pwd" />
저도 코드리뷰 반영하면서 바꾸려고 하는데 edittext 아래쪽에 textview로 경고문구를 표시하는 것보다 `TextInputLayout` 이걸 사용하는게 구현하기 더 편할 것 같더라고요...!

[공식문서](https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout) 놓고 갑니당

2022-12-04 07:47 UTC, waterminn commented on app/src/main/java/org/sopt/sample/util/extension/ContextExt.kt
>  }
확장함수를 이렇게 만들어서 쓰는군요 배워갑니다🤔 
귀찮음 조금이라도 덜 수 있는 것 같아서 저도 한번 써봐야겠네요...!

2022-12-04 07:47 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/main/home/HomeFragment.kt
> +    }
에러메시지를 observe하는 것보다 이렇게 서버통신 상태를 받아오는게 훨씬 로직이 깔끔해보이네요! 피드백 받은 부분인데 참고하고 갑니다👍

2022-12-05 13:16 UTC, b1urrrr commented on app/src/main/res/layout/activity_sign_up.xml
> +            app:layout_constraintTop_toBottomOf="@id/et_pwd" />
오오 TextInputLayout은 한번도 안 써봤는데 한번 알아봐야겠어요!
감사합니다 😊

2022-12-05 14:22 UTC, l2hyunwoo approved these changes
👍🏻

2022-12-05 14:22 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/data/local/State.kt
> +enum class State {
어떤 State인지 명시를 해주면 좋을 것 같아

2022-12-05 14:22 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/data/local/Type.kt
> +enum class Type {
이것도 마찬가지!

2022-12-05 14:22 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/util/binding/BindingAdapter.kt
> +    fun ImageView.setImage(imgUrl: String?) {
circlecrop 효과 있는 것 같은데 setImage라는 함수가 너무 포괄적이지 않을까?

2022-12-06 13:27 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/util/binding/BindingAdapter.kt
> +    fun ImageView.setImage(imgUrl: String?) {
포괄적인 네이밍이 많았네요 😅
수정했습니다 감사해요!

2022-12-06 13:28 UTC, merged