[과제] 7주차 세미나 과제
IN-SOPT-ANDROID/chaeyeon-jeon pull request #11
Opened 2022-12-10 14:58 UTC by b1urrrr

아몰라 일단 PR 올려~

2022-12-11 09:06 UTC, KWY0218 requested changes
작업하시느라 수고하셨습니다 ! ! !
그동안 과제 하시느라 고생하셨습니다 ~ ~ ~ ! ! ! 👍

2022-12-11 09:06 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/dto/request/RequestRegisterMusicDto.kt
> +    }.toString().toRequestBody("application/json".toMediaType())
나도 이거로 바꿔야지~ 😄

2022-12-11 09:06 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/dto/response/ResponseRegisterMusicDto.kt
> +)
앱잼을 하게 된다면,
`statusCode`, `success`, `message` 속성은 고정되어 있고, data의 타입만 계속 바뀔 것입니다.
이럴 때 wrapper class를 하나 만든다면 보일러 플레이트 코드를 줄일 수 있을 것 같습니다.
비록 지금은 이거 하나밖에 없지만 한번 wrapper class로 만들어 보는 것을 추천 드립니다 ~ !

2022-12-11 09:06 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/main/music/MusicFragment.kt
> +                )
가독성을 위해 else 사용을 지양하고, UiState 내에 있는 내용들 전부 when 절에 추가해주세요..!

2022-12-11 09:06 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/main/music/MusicAdapter.kt
> +class MusicAdapter(context: Context) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
지금 코드도 좋지만 한번 `ListAdapter`에 대해 공부해 보는 것을 추천드립니다!

2022-12-12 04:35 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/main/gallery/GalleryFragment.kt
> +    }
헉 이거 몰랐는데 알아갑니다 !!

2022-12-12 16:33 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/data/dto/request/RequestRegisterMusicDto.kt
> +    }.toString().toRequestBody("application/json".toMediaType())
바로 코드 리뷰하러 갑니다~👍

2022-12-13 11:25 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/data/dto/response/ResponseRegisterMusicDto.kt
> +)
꿀팁 감사합니다!
잘 써먹을게요~

2022-12-16 00:25 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/main/home/FollowerAdapter.kt
> +        }
1. `areItemsTheSame` 과, `areContentsTheSame` 다시 한번 찾아보시면 좋을 것 같습니다!
2. diff util 확장함수를 만들었지만 사용하지 않은 모습... 😭

2022-12-16 09:41 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/main/home/FollowerAdapter.kt
> +        }
둘이 거꾸로 생각하고 있었네요 ㅋㅋㅋㅋㅋㅋ😭
확장함수로 바꿨습니다! 빠른 리뷰 감사해요~

2022-12-16 09:48 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/main/music/MusicAdapter.kt
> +class MusicAdapter(context: Context) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
`ListAdapter`가 2주차 과제에 있었던 `NotifyDataSetChanged` 문제점을 개선한 기술이군요!
알려주셔서 감사합니다! 앞으로 잘 써봐야겠어요 ☺️

2022-12-16 09:51 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/main/gallery/GalleryFragment.kt
> +    }
```
/** hide keyboard from window */
fun Context.hideKeyboard(view: View) {
    val inputMethodManager = getSystemService(Activity.INPUT_METHOD_SERVICE) as InputMethodManager
    inputMethodManager.hideSoftInputFromWindow(view.windowToken, 0)
}
```
확장함수로 만들어놓은 함수입니다! ㅎㅎ

2022-12-16 15:18 UTC, KWY0218 commented on app/src/main/res/layout/fragment_home.xml
> +            app:layout_constraintVertical_bias="0.0"
`bias = "0.0" ` 특 마우스로 제약 걸다가 자신도 모르는 사이에 자동으로 생긴 것...
삭제해도 될 거 같습니다..!

2022-12-16 16:34 UTC, b1urrrr commented on app/src/main/res/layout/fragment_home.xml
> +            app:layout_constraintVertical_bias="0.0"
아놔~ 삭제했습니다!!

2022-12-18 05:14 UTC, KWY0218 approved these changes
LGTM 입니다~ 👍 마지막 과제도 하느라 고생했어요~ 😄👍

2022-12-18 09:53 UTC, merged