[과제] 4주차 세미나 필수 과제
IN-SOPT-ANDROID/chaeyeon-jeon pull request #7
Opened 2022-11-14 13:03 UTC by b1urrrr

- #6

## 필수 과제
- (진짜) 회원가입/로그인 기능 구현하기
- Home 화면 꾸미기

## 실행 화면
<img src="https://user-images.githubusercontent.com/70993562/201666336-df966ec3-0628-4d9d-acf8-90374c7c34ca.gif" width=30% height=30%>

2022-11-14 13:54 UTC, KWY0218 requested changes
과제 하시느라 고생하셨습니다!

서버 통신하는 로직을 viewmodel 에서
서버 통신 결과 값을 LiveData 에 저장하기
Activity 에선 ViewModel 내에 있는 LiveData 관찰하기

이런 통신 flow 를 한번 도전해 보는 걸 추천 드립니다!!

6주차 때 배울 내용이라서 다음 주 과제에서 해도 좋습니다 ~
수정 요청한 부분만 수정해도 좋습니다 ~

2022-11-14 13:54 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +            .baseUrl("http://3.39.169.52:3000/")
보안을 위해서 base url 을 local properties 내에 저장해서 사용하는 방식을 추천 드립니다.

2022-11-14 13:54 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +        .build()
`private val` 로 수정해도 될 것 같습니다

2022-11-14 13:54 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +    val retrofit by lazy {
해당 object에서만 사용하는 변수라면 private 로 변경해주세요 ~

2022-11-14 13:54 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/RequestLoginDTO.kt
> +    val password: String
변수 이름과 JSON 속성 이름이 일치할 때 `@SerialName` 을 굳이 안 붙여도 값이 들어옵니다.

2022-11-14 13:54 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/RequestLoginDTO.kt
> +data class RequestLoginDTO(
[code lab](https://developer.android.com/codelabs/basic-android-kotlin-training-intro-room-flow#4) 을 보시면
`DAO는 약어지만 Kotlin 코드의 이름 지정 규칙은 약어에서 첫 글자만 대문자로 표시하므로 이름이 ScheduleDAO가 아닌 ScheduleDao입니다.` 라고 나와있습니다.
그래서 DTO 말고 Dto 로 수정해주세요 ~

2022-11-14 13:54 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +        followerService.getFollowerList(1).enqueue(object : Callback<ResponseGetFollowerListDTO> {
서버 통신하는 해당 로직을 viewmodel 로 옮긴 후 viewmodel 내에 LiveData에 저장을 한 후,
activity에선 해당 LiveData 를 oberve 하는 로직으로 수정해주세요.

2022-11-14 13:54 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                context?.showSnackbar(binding.root, getString(R.string.msg_home_fail))
`requireContext()` 를 사용하면 non-nullable 한 context를 가지고 올 수 있어서 `?` 없앨 수 있습니다.
프래그먼트에서 context를 사용할 땐 `requireContext()` 애용해주세요!

2022-11-14 13:54 UTC, KWY0218 commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
`annotationProcessor` 의 경우 자바의 어노테이션 프로세싱 툴입니다. 
코틀린의 어노테이션 프로세싱 툴인 `kapt`를 쓰는 게 좋을 것 같습니다.

2022-11-14 16:09 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +    val retrofit by lazy {
이거 private으로 걸면 컴파일 에러 뜹니다.

2022-11-14 16:09 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +    var mHttpLoggingInterceptor = HttpLoggingInterceptor()
m 접두사는 Java Style이어서 접두사 빼시는걸 추천드립니다.

2022-11-14 16:13 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/data/remote/RequestLoginDTO.kt
> +data class RequestLoginDTO(
이건 제 실수긴 합니다 ^^

2022-11-14 16:15 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +        followerService.getFollowerList(1).enqueue(object : Callback<ResponseGetFollowerListDTO> {
아직 6주차 세미나를 안다뤄서..^^

2022-11-18 11:24 UTC, YuBeen-Park approved these changes
패키지 정리 굳굳~~~

2022-11-18 11:24 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/api/FollowerService.kt
> +        @Query("page") page: Int
오 저도 query문으로 수정해야겠네요오 
귀찮아서 그냥 통으로 넣어버린,,, ㅎㅎ

2022-11-18 11:24 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +        binding.etName.addTextChangedListener { checkSignupBtn() }
이렇게 코드 줄일 수 있군여
저도 깔끔하게 함수 리팩토링 해보겠습니다,, 
(전 사실 뷰모델이랑 livedata로 코드 줄여보고 싶었는데 대실패,, ㅎㅎ 담에 같이 모각코 어때여?)

2022-11-18 11:24 UTC, YuBeen-Park commented on 요약/seminar01/Chain & Flow.md
> +## 📍 VirtualLayout란?
요거는 처음 들어본거 같아요!

2022-11-21 10:25 UTC, KWY0218 approved these changes
LGTM 😄👍

2022-11-21 10:31 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +        followerService.getFollowerList(1).enqueue(object : Callback<ResponseGetFollowerListDTO> {
6주차 세미나 전까지 해보려했으나 처참히 실패했습니다...
다음 과제 때 반영해서 PR 올릴게요!!

2022-11-21 10:32 UTC, b1urrrr commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
구글링해서 이것저것 참고하다보니 자바식으로 코드를 쓴 부분이 많았네요😅 
감사합니다!!

2022-11-21 10:34 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +        binding.etName.addTextChangedListener { checkSignupBtn() }
공부하고 싶은 게 넘모 많네요... 😭
모각코 너무 좋아요!! 가보자구요 ~ 🔥🔥

2022-11-21 10:39 UTC, b1urrrr commented on 요약/seminar01/Chain & Flow.md
> +## 📍 VirtualLayout란?
저도 1주차 과제 때 처음 들어봤는데 한번 정리하고 보니까 유용한 기능 같아요!
앞으로 잘 써먹으려구요 😙

2022-11-22 15:20 UTC, merged

2022-11-22 17:57 UTC, waterminn reviewed
고생하셨습니다~!! 
한동안 정신이 없었더니 코드리뷰하는걸 잊어버렸었네요😭 6주차 과제에는 더 일찍 가겠습니당

2022-11-22 17:57 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                    binding.rvFollower.layoutManager = layoutManager
오 `SpanSizeLookup()` 은 처음 보는데 이걸 써야 헤더가 헤더 역할을 하는 것 같네요...! 새로운 걸 알아갑니다👍